# Generated by Django 3.1.6 on 2021-03-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('measure', models.IntegerField(choices=[(1, 'By Weight'), (2, 'By Quantity')], verbose_name='Kind of measure')),
                ('package', models.IntegerField(choices=[(1, '100 gr'), (2, '250 gr'), (3, '500 gr'), (4, '1 kg'), (5, '1'), (6, '4'), (7, '6'), (8, '12'), (9, '24')], verbose_name='Package size')),
                ('description', models.TextField(max_length=700)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
